# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled ,<summersmith> [<summersmith>, <summersmith>]
patreon: # Replace with a single Patreon <summersmith>
open_collective: # Replace with a single Open Collective <summersmith>
ko_fi: # Replace with a single Ko-fi <summersmith> <summersmith>
tidelift: # Replace with a single Tidelift platform-name/package-name <summersmith>, npm/babel
community_bridge: # Replace with a single Community Bridge project-name <summersmith>, cloud-foundry
liberapay: # Replace with a single Liberapay <summersmith>
issuehunt: # Replace with a single IssueHunt <summersmith>
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar <summersmith>
buy_me_a_coffee: # Replace with a single Buy Me a Coffee <summersmith>
thanks_dev: # Replace with a single thanks.dev <summersmith>
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
